name: Testing Context Variables
on:
  workflow_dispatch
env:
  cloud: google-cloud

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Context Variable"
        run: |
          echo "Repository Name : ${{ github.repository }}"
          echo "Workflow Name : ${{ github.workflow }}"
          echo "Triggered by : ${{ github.triggering_actor }}"
          echo "Function app name: ${{ vars.IDVERIFICATIONDEV }}"
          AZURE_FUNCTIONAPP_NAME: ${{ vars.IDVERIFICATIONDEV }}
  test_deploy:
    uses: ./.github/workflows/test_deploy.yml
    with:
      functionapp_name: ${{ vars.IDVERIFICATIONDEV }}
