name: Deploy Function App

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy (e.g., dev, stage, prod)'
        required: true
        type: string
      function_app_name:
        description: 'The function app name on Azure'
        required: true
        type: string
      package_name:
        description: 'The name of the package being deployed'
        required: true
        type: string
      package_path:
        description: 'The path to the function app package'
        required: true
        type: string
      publish_profile_secret_name:
        description: 'The secret name for the publish profile'
        required: true
        type: string

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  Deploy:
    runs-on: windows-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Release Type: ${{ inputs.functionapp_name }}"
          echo "Release Type: ${{ inputs.package_name }}"
          echo "Release Type: ${{ inputs.functionapp_package_path }}"
          echo "Release Type: ${{ inputs.environment }}"

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.package_name }}
          path: './${{ inputs.package_path }}bin/Release/net8.0'

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          package: './${{ inputs.package_path }}bin/Release/net8.0'
          publish-profile: ${{ secrets[inputs.publish_profile_secret_name] }}  # Access secret using name passed from the main workflow
          app-name: ${{ inputs.function_app_name }}
          environment: ${{ inputs.environment }}
