name: Develop

on:
  workflow_dispatch:

jobs:
  plan:
    environment:
      name: develop
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set environment variables
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_MSI=true" >> $GITHUB_ENV

      - name: Log in to Azure
        uses: Azure/login@v2.2.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: |
          terraform init 

      - name: Terraform Plan
        run: terraform plan -var-file ${{ vars.VAR_FILE_NAME }} -out ${{ vars.OUT_FILE_NAME }} 
