name: test_deployment

on: 
  workflow_call:
    inputs:
      functionapp_name:
        type: string
        required: true
      package_name:
        type: string
        required: true
      functionapp_package_path:
        type: string
        required: true
jobs:
  Deployment:
    runs-on: windows-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Release Type: ${{ inputs.functionapp_name }}"
          echo "Release Type: ${{ inputs.package_name }}"
          echo "Release Type: ${{ inputs.functionapp_package_path }}"
