name: test deployment

on: 
  workflow_call:
    inputs:
      functionapp_name:
        type: string
        required: true
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Release Type: ${{ inputs.functionapp_name }}"
