name: test deployment
on: 
  workflow_call:
  inputs:
    AZURE_FUNCTIONAPP_NAME:
    required: true
    type: string
jobs: 
  steps:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Context Variable"
        run: |
          echo "Functionapp Name : ${{ AZURE_FUNCTIONAPP_NAME }}"
